spring:
  application:
    name: msclientes

# Para subir a aplicação em uma porta aleatória
server:
  port: 0

# DefaultZone -> Coloco em qual servidor eureka eu quero registrar meu microservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
